spring:
  ai:
    vertex:
      ai:
        gemini:
          chat:
            options:
              model: gemini-2.0-flash
              temperature: 0.4
              max-output-tokens: 256
              max-tokens: 256
          project-id: protocol-playground
          location: us-central1

  grpc:
    server:
      ssl:
        secure: true
        client-auth: none
        bundle: server-http3
      port: 9443
  ssl:
    bundle:
      jks:
        server-http3:
          key:
            alias: http3
          keystore:
            location: classpath:keystore.p12
            password: ${JKS_PASSWORD}
